name : CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checking out of the repo
        uses: actions/checkout@v4
        
      - name: set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installing dependancies
        uses: npm install

      - name: running tests
        uses: npm test
